'use strict';

//This file is auto-generated by sequelize
const init = require('sequelize-init');
const fs = require('fs');
const path = require('path');
const Sequelize = require('sequelize');

const basename = path.basename(__filename);
const env = process.env.NODE_ENV || 'development';

const config = require('../config/config.json')[env];

let db = {};

if (config.use_env_variable) {
  var sequelize = new Sequelize(process.env[config.use_env_variable], config);
} else {
  var sequelize = new Sequelize(config.database, config.username, config.password, config);
}

fs
  .readdirSync(__dirname)
  .filter(file => {
    return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
  })
  .forEach(file => {
    var model = sequelize['import'](path.join(__dirname, file));
    db[model.name] = model;
  });

Object.keys(db).forEach(modelName => {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
});

//Models/tables
if (process.env.environment === "DEVELOPMENT") {
  console.log("DEVELOPMENT")
  db = init(sequelize, __dirname, { exclude: ['index.js'] });
}


db.sequelize = sequelize;
db.Sequelize = Sequelize;

db.PoliceDepartment = require('./policeDepartment')(sequelize, Sequelize);
db.PoliceOfficer = require('./policeOfficer')(sequelize, Sequelize);
db.Bike = require('./bike')(sequelize, Sequelize);

db.PoliceOfficer.belongsTo(db.PoliceDepartment, { foreignKey: 'departmentId', as: 'department' });
db.Bike.belongsTo(db.PoliceOfficer, { foreignKey: 'assignedOfficerId', as: 'assignedOfficer' });
module.exports = db;
